/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "djondb.so"

#include "runtime.h"
#include "cgocall.h"

#ifdef _64BIT
#define SWIG_PARM_SIZE 8
#else
#define SWIG_PARM_SIZE 4
#endif

#pragma dynimport _wrap_new_BSONObjVectorPtr__SWIG_0 _wrap_new_BSONObjVectorPtr__SWIG_0 ""
extern void (*_wrap_new_BSONObjVectorPtr__SWIG_0)(void*);
static void (*x_wrap_new_BSONObjVectorPtr__SWIG_0)(void*) = _wrap_new_BSONObjVectorPtr__SWIG_0;

void
·_swig_wrap_new_BSONObjVectorPtr__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_BSONObjVectorPtr__SWIG_0, &p);
}



#pragma dynimport _wrap_new_BSONObjVectorPtr__SWIG_1 _wrap_new_BSONObjVectorPtr__SWIG_1 ""
extern void (*_wrap_new_BSONObjVectorPtr__SWIG_1)(void*);
static void (*x_wrap_new_BSONObjVectorPtr__SWIG_1)(void*) = _wrap_new_BSONObjVectorPtr__SWIG_1;

void
·_swig_wrap_new_BSONObjVectorPtr__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_BSONObjVectorPtr__SWIG_1, &p);
}



#pragma dynimport _wrap_BSONObjVectorPtr_size _wrap_BSONObjVectorPtr_size ""
extern void (*_wrap_BSONObjVectorPtr_size)(void*);
static void (*x_wrap_BSONObjVectorPtr_size)(void*) = _wrap_BSONObjVectorPtr_size;

void
·_swig_wrap_BSONObjVectorPtr_size(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObjVectorPtr_size, &p);
}



#pragma dynimport _wrap_BSONObjVectorPtr_capacity _wrap_BSONObjVectorPtr_capacity ""
extern void (*_wrap_BSONObjVectorPtr_capacity)(void*);
static void (*x_wrap_BSONObjVectorPtr_capacity)(void*) = _wrap_BSONObjVectorPtr_capacity;

void
·_swig_wrap_BSONObjVectorPtr_capacity(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObjVectorPtr_capacity, &p);
}



#pragma dynimport _wrap_BSONObjVectorPtr_reserve _wrap_BSONObjVectorPtr_reserve ""
extern void (*_wrap_BSONObjVectorPtr_reserve)(void*);
static void (*x_wrap_BSONObjVectorPtr_reserve)(void*) = _wrap_BSONObjVectorPtr_reserve;

void
·_swig_wrap_BSONObjVectorPtr_reserve(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObjVectorPtr_reserve, &p);
}



#pragma dynimport _wrap_BSONObjVectorPtr_isEmpty _wrap_BSONObjVectorPtr_isEmpty ""
extern void (*_wrap_BSONObjVectorPtr_isEmpty)(void*);
static void (*x_wrap_BSONObjVectorPtr_isEmpty)(void*) = _wrap_BSONObjVectorPtr_isEmpty;

void
·_swig_wrap_BSONObjVectorPtr_isEmpty(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObjVectorPtr_isEmpty, &p);
}



#pragma dynimport _wrap_BSONObjVectorPtr_clear _wrap_BSONObjVectorPtr_clear ""
extern void (*_wrap_BSONObjVectorPtr_clear)(void*);
static void (*x_wrap_BSONObjVectorPtr_clear)(void*) = _wrap_BSONObjVectorPtr_clear;

void
·_swig_wrap_BSONObjVectorPtr_clear(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObjVectorPtr_clear, &p);
}



#pragma dynimport _wrap_BSONObjVectorPtr_add _wrap_BSONObjVectorPtr_add ""
extern void (*_wrap_BSONObjVectorPtr_add)(void*);
static void (*x_wrap_BSONObjVectorPtr_add)(void*) = _wrap_BSONObjVectorPtr_add;

void
·_swig_wrap_BSONObjVectorPtr_add(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObjVectorPtr_add, &p);
}



#pragma dynimport _wrap_BSONObjVectorPtr_get _wrap_BSONObjVectorPtr_get ""
extern void (*_wrap_BSONObjVectorPtr_get)(void*);
static void (*x_wrap_BSONObjVectorPtr_get)(void*) = _wrap_BSONObjVectorPtr_get;

void
·_swig_wrap_BSONObjVectorPtr_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObjVectorPtr_get, &p);
}



#pragma dynimport _wrap_BSONObjVectorPtr_set _wrap_BSONObjVectorPtr_set ""
extern void (*_wrap_BSONObjVectorPtr_set)(void*);
static void (*x_wrap_BSONObjVectorPtr_set)(void*) = _wrap_BSONObjVectorPtr_set;

void
·_swig_wrap_BSONObjVectorPtr_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObjVectorPtr_set, &p);
}



#pragma dynimport _wrap_delete_BSONObjVectorPtr _wrap_delete_BSONObjVectorPtr ""
extern void (*_wrap_delete_BSONObjVectorPtr)(void*);
static void (*x_wrap_delete_BSONObjVectorPtr)(void*) = _wrap_delete_BSONObjVectorPtr;

void
·_swig_wrap_delete_BSONObjVectorPtr(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_BSONObjVectorPtr, &p);
}



#pragma dynimport _wrap_new_StringVector__SWIG_0 _wrap_new_StringVector__SWIG_0 ""
extern void (*_wrap_new_StringVector__SWIG_0)(void*);
static void (*x_wrap_new_StringVector__SWIG_0)(void*) = _wrap_new_StringVector__SWIG_0;

void
·_swig_wrap_new_StringVector__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_StringVector__SWIG_0, &p);
}



#pragma dynimport _wrap_new_StringVector__SWIG_1 _wrap_new_StringVector__SWIG_1 ""
extern void (*_wrap_new_StringVector__SWIG_1)(void*);
static void (*x_wrap_new_StringVector__SWIG_1)(void*) = _wrap_new_StringVector__SWIG_1;

void
·_swig_wrap_new_StringVector__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_StringVector__SWIG_1, &p);
}



#pragma dynimport _wrap_StringVector_size _wrap_StringVector_size ""
extern void (*_wrap_StringVector_size)(void*);
static void (*x_wrap_StringVector_size)(void*) = _wrap_StringVector_size;

void
·_swig_wrap_StringVector_size(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_size, &p);
}



#pragma dynimport _wrap_StringVector_capacity _wrap_StringVector_capacity ""
extern void (*_wrap_StringVector_capacity)(void*);
static void (*x_wrap_StringVector_capacity)(void*) = _wrap_StringVector_capacity;

void
·_swig_wrap_StringVector_capacity(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_capacity, &p);
}



#pragma dynimport _wrap_StringVector_reserve _wrap_StringVector_reserve ""
extern void (*_wrap_StringVector_reserve)(void*);
static void (*x_wrap_StringVector_reserve)(void*) = _wrap_StringVector_reserve;

void
·_swig_wrap_StringVector_reserve(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_reserve, &p);
}



#pragma dynimport _wrap_StringVector_isEmpty _wrap_StringVector_isEmpty ""
extern void (*_wrap_StringVector_isEmpty)(void*);
static void (*x_wrap_StringVector_isEmpty)(void*) = _wrap_StringVector_isEmpty;

void
·_swig_wrap_StringVector_isEmpty(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_isEmpty, &p);
}



#pragma dynimport _wrap_StringVector_clear _wrap_StringVector_clear ""
extern void (*_wrap_StringVector_clear)(void*);
static void (*x_wrap_StringVector_clear)(void*) = _wrap_StringVector_clear;

void
·_swig_wrap_StringVector_clear(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_StringVector_clear, &p);
}



#pragma dynimport _wrap_StringVector_add _wrap_StringVector_add ""
extern void (*_wrap_StringVector_add)(void*);
static void (*x_wrap_StringVector_add)(void*) = _wrap_StringVector_add;

void
·_swig_wrap_StringVector_add(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_StringVector_add, &p);
}



#pragma dynimport _wrap_StringVector_get _wrap_StringVector_get ""
extern void (*_wrap_StringVector_get)(void*);
static void (*x_wrap_StringVector_get)(void*) = _wrap_StringVector_get;

void
·_swig_wrap_StringVector_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_StringVector_get, &p);
}



#pragma dynimport _wrap_StringVector_set _wrap_StringVector_set ""
extern void (*_wrap_StringVector_set)(void*);
static void (*x_wrap_StringVector_set)(void*) = _wrap_StringVector_set;

void
·_swig_wrap_StringVector_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_StringVector_set, &p);
}



#pragma dynimport _wrap_delete_StringVector _wrap_delete_StringVector ""
extern void (*_wrap_delete_StringVector)(void*);
static void (*x_wrap_delete_StringVector)(void*) = _wrap_delete_StringVector;

void
·_swig_wrap_delete_StringVector(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_StringVector, &p);
}



#pragma dynimport _wrap_new_BSONArrayObj__SWIG_0 _wrap_new_BSONArrayObj__SWIG_0 ""
extern void (*_wrap_new_BSONArrayObj__SWIG_0)(void*);
static void (*x_wrap_new_BSONArrayObj__SWIG_0)(void*) = _wrap_new_BSONArrayObj__SWIG_0;

void
·_swig_wrap_new_BSONArrayObj__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_BSONArrayObj__SWIG_0, &p);
}



#pragma dynimport _wrap_delete_BSONArrayObj _wrap_delete_BSONArrayObj ""
extern void (*_wrap_delete_BSONArrayObj)(void*);
static void (*x_wrap_delete_BSONArrayObj)(void*) = _wrap_delete_BSONArrayObj;

void
·_swig_wrap_delete_BSONArrayObj(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_BSONArrayObj, &p);
}



#pragma dynimport _wrap_new_BSONArrayObj__SWIG_1 _wrap_new_BSONArrayObj__SWIG_1 ""
extern void (*_wrap_new_BSONArrayObj__SWIG_1)(void*);
static void (*x_wrap_new_BSONArrayObj__SWIG_1)(void*) = _wrap_new_BSONArrayObj__SWIG_1;

void
·_swig_wrap_new_BSONArrayObj__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_BSONArrayObj__SWIG_1, &p);
}



#pragma dynimport _wrap_BSONArrayObj_length _wrap_BSONArrayObj_length ""
extern void (*_wrap_BSONArrayObj_length)(void*);
static void (*x_wrap_BSONArrayObj_length)(void*) = _wrap_BSONArrayObj_length;

void
·_swig_wrap_BSONArrayObj_length(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_length, &p);
}



#pragma dynimport _wrap_BSONArrayObj_add _wrap_BSONArrayObj_add ""
extern void (*_wrap_BSONArrayObj_add)(void*);
static void (*x_wrap_BSONArrayObj_add)(void*) = _wrap_BSONArrayObj_add;

void
·_swig_wrap_BSONArrayObj_add(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_add, &p);
}



#pragma dynimport _wrap_BSONArrayObj_addAll _wrap_BSONArrayObj_addAll ""
extern void (*_wrap_BSONArrayObj_addAll)(void*);
static void (*x_wrap_BSONArrayObj_addAll)(void*) = _wrap_BSONArrayObj_addAll;

void
·_swig_wrap_BSONArrayObj_addAll(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_addAll, &p);
}



#pragma dynimport _wrap_BSONArrayObj_get _wrap_BSONArrayObj_get ""
extern void (*_wrap_BSONArrayObj_get)(void*);
static void (*x_wrap_BSONArrayObj_get)(void*) = _wrap_BSONArrayObj_get;

void
·_swig_wrap_BSONArrayObj_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_get, &p);
}



#pragma dynimport _wrap_BSONArrayObj_toChar _wrap_BSONArrayObj_toChar ""
extern void (*_wrap_BSONArrayObj_toChar)(void*);
static void (*x_wrap_BSONArrayObj_toChar)(void*) = _wrap_BSONArrayObj_toChar;

void
·_swig_wrap_BSONArrayObj_toChar(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_toChar, &p);
}



#pragma dynimport _wrap_BSONArrayObj_Xselect _wrap_BSONArrayObj_Xselect ""
extern void (*_wrap_BSONArrayObj_Xselect)(void*);
static void (*x_wrap_BSONArrayObj_Xselect)(void*) = _wrap_BSONArrayObj_Xselect;

void
·_swig_wrap_BSONArrayObj_Xselect(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_Xselect, &p);
}



#pragma dynimport _wrap_BSONArrayObj_begin__SWIG_0 _wrap_BSONArrayObj_begin__SWIG_0 ""
extern void (*_wrap_BSONArrayObj_begin__SWIG_0)(void*);
static void (*x_wrap_BSONArrayObj_begin__SWIG_0)(void*) = _wrap_BSONArrayObj_begin__SWIG_0;

void
·_swig_wrap_BSONArrayObj_begin__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_begin__SWIG_0, &p);
}



#pragma dynimport _wrap_BSONArrayObj_end__SWIG_0 _wrap_BSONArrayObj_end__SWIG_0 ""
extern void (*_wrap_BSONArrayObj_end__SWIG_0)(void*);
static void (*x_wrap_BSONArrayObj_end__SWIG_0)(void*) = _wrap_BSONArrayObj_end__SWIG_0;

void
·_swig_wrap_BSONArrayObj_end__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_end__SWIG_0, &p);
}



#pragma dynimport _wrap_BSONArrayObj_begin__SWIG_1 _wrap_BSONArrayObj_begin__SWIG_1 ""
extern void (*_wrap_BSONArrayObj_begin__SWIG_1)(void*);
static void (*x_wrap_BSONArrayObj_begin__SWIG_1)(void*) = _wrap_BSONArrayObj_begin__SWIG_1;

void
·_swig_wrap_BSONArrayObj_begin__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_begin__SWIG_1, &p);
}



#pragma dynimport _wrap_BSONArrayObj_end__SWIG_1 _wrap_BSONArrayObj_end__SWIG_1 ""
extern void (*_wrap_BSONArrayObj_end__SWIG_1)(void*);
static void (*x_wrap_BSONArrayObj_end__SWIG_1)(void*) = _wrap_BSONArrayObj_end__SWIG_1;

void
·_swig_wrap_BSONArrayObj_end__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONArrayObj_end__SWIG_1, &p);
}



#pragma dynimport _wrap_new_BSONObj__SWIG_0 _wrap_new_BSONObj__SWIG_0 ""
extern void (*_wrap_new_BSONObj__SWIG_0)(void*);
static void (*x_wrap_new_BSONObj__SWIG_0)(void*) = _wrap_new_BSONObj__SWIG_0;

void
·_swig_wrap_new_BSONObj__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_BSONObj__SWIG_0, &p);
}



#pragma dynimport _wrap_new_BSONObj__SWIG_1 _wrap_new_BSONObj__SWIG_1 ""
extern void (*_wrap_new_BSONObj__SWIG_1)(void*);
static void (*x_wrap_new_BSONObj__SWIG_1)(void*) = _wrap_new_BSONObj__SWIG_1;

void
·_swig_wrap_new_BSONObj__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_BSONObj__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_BSONObj _wrap_delete_BSONObj ""
extern void (*_wrap_delete_BSONObj)(void*);
static void (*x_wrap_delete_BSONObj)(void*) = _wrap_delete_BSONObj;

void
·_swig_wrap_delete_BSONObj(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_BSONObj, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_0 _wrap_BSONObj_add__SWIG_0 ""
extern void (*_wrap_BSONObj_add__SWIG_0)(void*);
static void (*x_wrap_BSONObj_add__SWIG_0)(void*) = _wrap_BSONObj_add__SWIG_0;

void
·_swig_wrap_BSONObj_add__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_0, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_1 _wrap_BSONObj_add__SWIG_1 ""
extern void (*_wrap_BSONObj_add__SWIG_1)(void*);
static void (*x_wrap_BSONObj_add__SWIG_1)(void*) = _wrap_BSONObj_add__SWIG_1;

void
·_swig_wrap_BSONObj_add__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + 8];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_1, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_2 _wrap_BSONObj_add__SWIG_2 ""
extern void (*_wrap_BSONObj_add__SWIG_2)(void*);
static void (*x_wrap_BSONObj_add__SWIG_2)(void*) = _wrap_BSONObj_add__SWIG_2;

void
·_swig_wrap_BSONObj_add__SWIG_2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_2, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_3 _wrap_BSONObj_add__SWIG_3 ""
extern void (*_wrap_BSONObj_add__SWIG_3)(void*);
static void (*x_wrap_BSONObj_add__SWIG_3)(void*) = _wrap_BSONObj_add__SWIG_3;

void
·_swig_wrap_BSONObj_add__SWIG_3(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_3, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_4 _wrap_BSONObj_add__SWIG_4 ""
extern void (*_wrap_BSONObj_add__SWIG_4)(void*);
static void (*x_wrap_BSONObj_add__SWIG_4)(void*) = _wrap_BSONObj_add__SWIG_4;

void
·_swig_wrap_BSONObj_add__SWIG_4(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_4, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_5 _wrap_BSONObj_add__SWIG_5 ""
extern void (*_wrap_BSONObj_add__SWIG_5)(void*);
static void (*x_wrap_BSONObj_add__SWIG_5)(void*) = _wrap_BSONObj_add__SWIG_5;

void
·_swig_wrap_BSONObj_add__SWIG_5(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_5, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_6 _wrap_BSONObj_add__SWIG_6 ""
extern void (*_wrap_BSONObj_add__SWIG_6)(void*);
static void (*x_wrap_BSONObj_add__SWIG_6)(void*) = _wrap_BSONObj_add__SWIG_6;

void
·_swig_wrap_BSONObj_add__SWIG_6(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_6, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_7 _wrap_BSONObj_add__SWIG_7 ""
extern void (*_wrap_BSONObj_add__SWIG_7)(void*);
static void (*x_wrap_BSONObj_add__SWIG_7)(void*) = _wrap_BSONObj_add__SWIG_7;

void
·_swig_wrap_BSONObj_add__SWIG_7(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_7, &p);
}



#pragma dynimport _wrap_BSONObj_add__SWIG_8 _wrap_BSONObj_add__SWIG_8 ""
extern void (*_wrap_BSONObj_add__SWIG_8)(void*);
static void (*x_wrap_BSONObj_add__SWIG_8)(void*) = _wrap_BSONObj_add__SWIG_8;

void
·_swig_wrap_BSONObj_add__SWIG_8(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_add__SWIG_8, &p);
}



#pragma dynimport _wrap_BSONObj_has _wrap_BSONObj_has ""
extern void (*_wrap_BSONObj_has)(void*);
static void (*x_wrap_BSONObj_has)(void*) = _wrap_BSONObj_has;

void
·_swig_wrap_BSONObj_has(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_has, &p);
}



#pragma dynimport _wrap_BSONObj_getBoolean _wrap_BSONObj_getBoolean ""
extern void (*_wrap_BSONObj_getBoolean)(void*);
static void (*x_wrap_BSONObj_getBoolean)(void*) = _wrap_BSONObj_getBoolean;

void
·_swig_wrap_BSONObj_getBoolean(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getBoolean, &p);
}



#pragma dynimport _wrap_BSONObj_getInt _wrap_BSONObj_getInt ""
extern void (*_wrap_BSONObj_getInt)(void*);
static void (*x_wrap_BSONObj_getInt)(void*) = _wrap_BSONObj_getInt;

void
·_swig_wrap_BSONObj_getInt(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getInt, &p);
}



#pragma dynimport _wrap_BSONObj_getDouble _wrap_BSONObj_getDouble ""
extern void (*_wrap_BSONObj_getDouble)(void*);
static void (*x_wrap_BSONObj_getDouble)(void*) = _wrap_BSONObj_getDouble;

void
·_swig_wrap_BSONObj_getDouble(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + 8];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getDouble, &p);
}



#pragma dynimport _wrap_BSONObj_getLong _wrap_BSONObj_getLong ""
extern void (*_wrap_BSONObj_getLong)(void*);
static void (*x_wrap_BSONObj_getLong)(void*) = _wrap_BSONObj_getLong;

void
·_swig_wrap_BSONObj_getLong(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getLong, &p);
}



#pragma dynimport _wrap_BSONObj_getString _wrap_BSONObj_getString ""
extern void (*_wrap_BSONObj_getString)(void*);
static void (*x_wrap_BSONObj_getString)(void*) = _wrap_BSONObj_getString;

void
·_swig_wrap_BSONObj_getString(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getString, &p);
}



#pragma dynimport _wrap_BSONObj_getBSON _wrap_BSONObj_getBSON ""
extern void (*_wrap_BSONObj_getBSON)(void*);
static void (*x_wrap_BSONObj_getBSON)(void*) = _wrap_BSONObj_getBSON;

void
·_swig_wrap_BSONObj_getBSON(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getBSON, &p);
}



#pragma dynimport _wrap_BSONObj_getBSONArray _wrap_BSONObj_getBSONArray ""
extern void (*_wrap_BSONObj_getBSONArray)(void*);
static void (*x_wrap_BSONObj_getBSONArray)(void*) = _wrap_BSONObj_getBSONArray;

void
·_swig_wrap_BSONObj_getBSONArray(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getBSONArray, &p);
}



#pragma dynimport _wrap_BSONObj_get _wrap_BSONObj_get ""
extern void (*_wrap_BSONObj_get)(void*);
static void (*x_wrap_BSONObj_get)(void*) = _wrap_BSONObj_get;

void
·_swig_wrap_BSONObj_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_get, &p);
}



#pragma dynimport _wrap_BSONObj_getContent__SWIG_0 _wrap_BSONObj_getContent__SWIG_0 ""
extern void (*_wrap_BSONObj_getContent__SWIG_0)(void*);
static void (*x_wrap_BSONObj_getContent__SWIG_0)(void*) = _wrap_BSONObj_getContent__SWIG_0;

void
·_swig_wrap_BSONObj_getContent__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getContent__SWIG_0, &p);
}



#pragma dynimport _wrap_BSONObj_getContent__SWIG_1 _wrap_BSONObj_getContent__SWIG_1 ""
extern void (*_wrap_BSONObj_getContent__SWIG_1)(void*);
static void (*x_wrap_BSONObj_getContent__SWIG_1)(void*) = _wrap_BSONObj_getContent__SWIG_1;

void
·_swig_wrap_BSONObj_getContent__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getContent__SWIG_1, &p);
}



#pragma dynimport _wrap_BSONObj_getXpath _wrap_BSONObj_getXpath ""
extern void (*_wrap_BSONObj_getXpath)(void*);
static void (*x_wrap_BSONObj_getXpath)(void*) = _wrap_BSONObj_getXpath;

void
·_swig_wrap_BSONObj_getXpath(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_getXpath, &p);
}



#pragma dynimport _wrap_BSONObj_Xselect _wrap_BSONObj_Xselect ""
extern void (*_wrap_BSONObj_Xselect)(void*);
static void (*x_wrap_BSONObj_Xselect)(void*) = _wrap_BSONObj_Xselect;

void
·_swig_wrap_BSONObj_Xselect(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_Xselect, &p);
}



#pragma dynimport _wrap_BSONObj_Xtype _wrap_BSONObj_Xtype ""
extern void (*_wrap_BSONObj_Xtype)(void*);
static void (*x_wrap_BSONObj_Xtype)(void*) = _wrap_BSONObj_Xtype;

void
·_swig_wrap_BSONObj_Xtype(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_Xtype, &p);
}



#pragma dynimport _wrap_BSONObj_toChar _wrap_BSONObj_toChar ""
extern void (*_wrap_BSONObj_toChar)(void*);
static void (*x_wrap_BSONObj_toChar)(void*) = _wrap_BSONObj_toChar;

void
·_swig_wrap_BSONObj_toChar(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_toChar, &p);
}



#pragma dynimport _wrap_BSONObj_begin _wrap_BSONObj_begin ""
extern void (*_wrap_BSONObj_begin)(void*);
static void (*x_wrap_BSONObj_begin)(void*) = _wrap_BSONObj_begin;

void
·_swig_wrap_BSONObj_begin(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_begin, &p);
}



#pragma dynimport _wrap_BSONObj_end _wrap_BSONObj_end ""
extern void (*_wrap_BSONObj_end)(void*);
static void (*x_wrap_BSONObj_end)(void*) = _wrap_BSONObj_end;

void
·_swig_wrap_BSONObj_end(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_end, &p);
}



#pragma dynimport _wrap_BSONObj_length _wrap_BSONObj_length ""
extern void (*_wrap_BSONObj_length)(void*);
static void (*x_wrap_BSONObj_length)(void*) = _wrap_BSONObj_length;

void
·_swig_wrap_BSONObj_length(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONObj_length, &p);
}



#pragma dynimport _wrap_new_BSONParser _wrap_new_BSONParser ""
extern void (*_wrap_new_BSONParser)(void*);
static void (*x_wrap_new_BSONParser)(void*) = _wrap_new_BSONParser;

void
·_swig_wrap_new_BSONParser(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_BSONParser, &p);
}



#pragma dynimport _wrap_delete_BSONParser _wrap_delete_BSONParser ""
extern void (*_wrap_delete_BSONParser)(void*);
static void (*x_wrap_delete_BSONParser)(void*) = _wrap_delete_BSONParser;

void
·_swig_wrap_delete_BSONParser(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_BSONParser, &p);
}



#pragma dynimport _wrap_BSONParser_parse _wrap_BSONParser_parse ""
extern void (*_wrap_BSONParser_parse)(void*);
static void (*x_wrap_BSONParser_parse)(void*) = _wrap_BSONParser_parse;

void
·_swig_wrap_BSONParser_parse(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONParser_parse, &p);
}



#pragma dynimport _wrap_BSONParser_parseArray _wrap_BSONParser_parseArray ""
extern void (*_wrap_BSONParser_parseArray)(void*);
static void (*x_wrap_BSONParser_parseArray)(void*) = _wrap_BSONParser_parseArray;

void
·_swig_wrap_BSONParser_parseArray(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BSONParser_parseArray, &p);
}



#pragma dynimport _wrap_FO_NONE _wrap_FO_NONE ""
extern void (*_wrap_FO_NONE)(void*);
static void (*x_wrap_FO_NONE)(void*) = _wrap_FO_NONE;

void
·_swig_getFO_NONE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_NONE, &p);
}



#pragma dynimport _wrap_FO_TOKEN _wrap_FO_TOKEN ""
extern void (*_wrap_FO_TOKEN)(void*);
static void (*x_wrap_FO_TOKEN)(void*) = _wrap_FO_TOKEN;

void
·_swig_getFO_TOKEN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_TOKEN, &p);
}



#pragma dynimport _wrap_FO_AND _wrap_FO_AND ""
extern void (*_wrap_FO_AND)(void*);
static void (*x_wrap_FO_AND)(void*) = _wrap_FO_AND;

void
·_swig_getFO_AND(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_AND, &p);
}



#pragma dynimport _wrap_FO_OR _wrap_FO_OR ""
extern void (*_wrap_FO_OR)(void*);
static void (*x_wrap_FO_OR)(void*) = _wrap_FO_OR;

void
·_swig_getFO_OR(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_OR, &p);
}



#pragma dynimport _wrap_FO_EQUALS _wrap_FO_EQUALS ""
extern void (*_wrap_FO_EQUALS)(void*);
static void (*x_wrap_FO_EQUALS)(void*) = _wrap_FO_EQUALS;

void
·_swig_getFO_EQUALS(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_EQUALS, &p);
}



#pragma dynimport _wrap_FO_NOT_EQUALS _wrap_FO_NOT_EQUALS ""
extern void (*_wrap_FO_NOT_EQUALS)(void*);
static void (*x_wrap_FO_NOT_EQUALS)(void*) = _wrap_FO_NOT_EQUALS;

void
·_swig_getFO_NOT_EQUALS(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_NOT_EQUALS, &p);
}



#pragma dynimport _wrap_FO_PARENTESIS_OPEN _wrap_FO_PARENTESIS_OPEN ""
extern void (*_wrap_FO_PARENTESIS_OPEN)(void*);
static void (*x_wrap_FO_PARENTESIS_OPEN)(void*) = _wrap_FO_PARENTESIS_OPEN;

void
·_swig_getFO_PARENTESIS_OPEN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_PARENTESIS_OPEN, &p);
}



#pragma dynimport _wrap_FO_PARENTESIS_CLOSE _wrap_FO_PARENTESIS_CLOSE ""
extern void (*_wrap_FO_PARENTESIS_CLOSE)(void*);
static void (*x_wrap_FO_PARENTESIS_CLOSE)(void*) = _wrap_FO_PARENTESIS_CLOSE;

void
·_swig_getFO_PARENTESIS_CLOSE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_PARENTESIS_CLOSE, &p);
}



#pragma dynimport _wrap_FO_NOT _wrap_FO_NOT ""
extern void (*_wrap_FO_NOT)(void*);
static void (*x_wrap_FO_NOT)(void*) = _wrap_FO_NOT;

void
·_swig_getFO_NOT(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_NOT, &p);
}



#pragma dynimport _wrap_FO_LESSTHAN _wrap_FO_LESSTHAN ""
extern void (*_wrap_FO_LESSTHAN)(void*);
static void (*x_wrap_FO_LESSTHAN)(void*) = _wrap_FO_LESSTHAN;

void
·_swig_getFO_LESSTHAN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_LESSTHAN, &p);
}



#pragma dynimport _wrap_FO_LESSEQUALTHAN _wrap_FO_LESSEQUALTHAN ""
extern void (*_wrap_FO_LESSEQUALTHAN)(void*);
static void (*x_wrap_FO_LESSEQUALTHAN)(void*) = _wrap_FO_LESSEQUALTHAN;

void
·_swig_getFO_LESSEQUALTHAN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_LESSEQUALTHAN, &p);
}



#pragma dynimport _wrap_FO_GREATERTHAN _wrap_FO_GREATERTHAN ""
extern void (*_wrap_FO_GREATERTHAN)(void*);
static void (*x_wrap_FO_GREATERTHAN)(void*) = _wrap_FO_GREATERTHAN;

void
·_swig_getFO_GREATERTHAN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_GREATERTHAN, &p);
}



#pragma dynimport _wrap_FO_GREATEREQUALTHAN _wrap_FO_GREATEREQUALTHAN ""
extern void (*_wrap_FO_GREATEREQUALTHAN)(void*);
static void (*x_wrap_FO_GREATEREQUALTHAN)(void*) = _wrap_FO_GREATEREQUALTHAN;

void
·_swig_getFO_GREATEREQUALTHAN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_GREATEREQUALTHAN, &p);
}



#pragma dynimport _wrap_FO_EXISTS _wrap_FO_EXISTS ""
extern void (*_wrap_FO_EXISTS)(void*);
static void (*x_wrap_FO_EXISTS)(void*) = _wrap_FO_EXISTS;

void
·_swig_getFO_EXISTS(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_FO_EXISTS, &p);
}



#pragma dynimport _wrap_ET_CONSTANT _wrap_ET_CONSTANT ""
extern void (*_wrap_ET_CONSTANT)(void*);
static void (*x_wrap_ET_CONSTANT)(void*) = _wrap_ET_CONSTANT;

void
·_swig_getET_CONSTANT(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ET_CONSTANT, &p);
}



#pragma dynimport _wrap_ET_SIMPLE _wrap_ET_SIMPLE ""
extern void (*_wrap_ET_SIMPLE)(void*);
static void (*x_wrap_ET_SIMPLE)(void*) = _wrap_ET_SIMPLE;

void
·_swig_getET_SIMPLE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ET_SIMPLE, &p);
}



#pragma dynimport _wrap_ET_BINARY _wrap_ET_BINARY ""
extern void (*_wrap_ET_BINARY)(void*);
static void (*x_wrap_ET_BINARY)(void*) = _wrap_ET_BINARY;

void
·_swig_getET_BINARY(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ET_BINARY, &p);
}



#pragma dynimport _wrap_ET_UNARY _wrap_ET_UNARY ""
extern void (*_wrap_ET_UNARY)(void*);
static void (*x_wrap_ET_UNARY)(void*) = _wrap_ET_UNARY;

void
·_swig_getET_UNARY(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ET_UNARY, &p);
}



#pragma dynimport _wrap_parseFilterOperator _wrap_parseFilterOperator ""
extern void (*_wrap_parseFilterOperator)(void*);
static void (*x_wrap_parseFilterOperator)(void*) = _wrap_parseFilterOperator;

void
·ParseFilterOperator(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_parseFilterOperator, &p);
}



#pragma dynimport _wrap_new_ParseException__SWIG_0 _wrap_new_ParseException__SWIG_0 ""
extern void (*_wrap_new_ParseException__SWIG_0)(void*);
static void (*x_wrap_new_ParseException__SWIG_0)(void*) = _wrap_new_ParseException__SWIG_0;

void
·_swig_wrap_new_ParseException__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_ParseException__SWIG_0, &p);
}



#pragma dynimport _wrap_new_ParseException__SWIG_1 _wrap_new_ParseException__SWIG_1 ""
extern void (*_wrap_new_ParseException__SWIG_1)(void*);
static void (*x_wrap_new_ParseException__SWIG_1)(void*) = _wrap_new_ParseException__SWIG_1;

void
·_swig_wrap_new_ParseException__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_ParseException__SWIG_1, &p);
}



#pragma dynimport _wrap_ParseException_what _wrap_ParseException_what ""
extern void (*_wrap_ParseException_what)(void*);
static void (*x_wrap_ParseException_what)(void*) = _wrap_ParseException_what;

void
·_swig_wrap_ParseException_what(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_ParseException_what, &p);
}



#pragma dynimport _wrap_ParseException_errorCode _wrap_ParseException_errorCode ""
extern void (*_wrap_ParseException_errorCode)(void*);
static void (*x_wrap_ParseException_errorCode)(void*) = _wrap_ParseException_errorCode;

void
·_swig_wrap_ParseException_errorCode(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ParseException_errorCode, &p);
}



#pragma dynimport _wrap_delete_ParseException _wrap_delete_ParseException ""
extern void (*_wrap_delete_ParseException)(void*);
static void (*x_wrap_delete_ParseException)(void*) = _wrap_delete_ParseException;

void
·_swig_wrap_delete_ParseException(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_ParseException, &p);
}



#pragma dynimport _wrap_bson_splitSelect _wrap_bson_splitSelect ""
extern void (*_wrap_bson_splitSelect)(void*);
static void (*x_wrap_bson_splitSelect)(void*) = _wrap_bson_splitSelect;

void
·_swig_wrap_bson_splitSelect(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_bson_splitSelect, &p);
}



#pragma dynimport _wrap_bson_subselect _wrap_bson_subselect ""
extern void (*_wrap_bson_subselect)(void*);
static void (*x_wrap_bson_subselect)(void*) = _wrap_bson_subselect;

void
·Bson_subselect(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_bson_subselect, &p);
}



#pragma dynimport _wrap_convert _wrap_convert ""
extern void (*_wrap_convert)(void*);
static void (*x_wrap_convert)(void*) = _wrap_convert;

void
·_swig_wrap_convert(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_convert, &p);
}



#pragma dynimport _wrap_new_DjondbConnection__SWIG_0 _wrap_new_DjondbConnection__SWIG_0 ""
extern void (*_wrap_new_DjondbConnection__SWIG_0)(void*);
static void (*x_wrap_new_DjondbConnection__SWIG_0)(void*) = _wrap_new_DjondbConnection__SWIG_0;

void
·_swig_wrap_new_DjondbConnection__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_DjondbConnection__SWIG_0, &p);
}



#pragma dynimport _wrap_new_DjondbConnection__SWIG_1 _wrap_new_DjondbConnection__SWIG_1 ""
extern void (*_wrap_new_DjondbConnection__SWIG_1)(void*);
static void (*x_wrap_new_DjondbConnection__SWIG_1)(void*) = _wrap_new_DjondbConnection__SWIG_1;

void
·_swig_wrap_new_DjondbConnection__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_DjondbConnection__SWIG_1, &p);
}



#pragma dynimport _wrap_new_DjondbConnection__SWIG_2 _wrap_new_DjondbConnection__SWIG_2 ""
extern void (*_wrap_new_DjondbConnection__SWIG_2)(void*);
static void (*x_wrap_new_DjondbConnection__SWIG_2)(void*) = _wrap_new_DjondbConnection__SWIG_2;

void
·_swig_wrap_new_DjondbConnection__SWIG_2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_DjondbConnection__SWIG_2, &p);
}



#pragma dynimport _wrap_delete_DjondbConnection _wrap_delete_DjondbConnection ""
extern void (*_wrap_delete_DjondbConnection)(void*);
static void (*x_wrap_delete_DjondbConnection)(void*) = _wrap_delete_DjondbConnection;

void
·_swig_wrap_delete_DjondbConnection(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_DjondbConnection, &p);
}



#pragma dynimport _wrap_DjondbConnection_beginTransaction _wrap_DjondbConnection_beginTransaction ""
extern void (*_wrap_DjondbConnection_beginTransaction)(void*);
static void (*x_wrap_DjondbConnection_beginTransaction)(void*) = _wrap_DjondbConnection_beginTransaction;

void
·_swig_wrap_DjondbConnection_beginTransaction(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_beginTransaction, &p);
}



#pragma dynimport _wrap_DjondbConnection_commitTransaction _wrap_DjondbConnection_commitTransaction ""
extern void (*_wrap_DjondbConnection_commitTransaction)(void*);
static void (*x_wrap_DjondbConnection_commitTransaction)(void*) = _wrap_DjondbConnection_commitTransaction;

void
·_swig_wrap_DjondbConnection_commitTransaction(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_commitTransaction, &p);
}



#pragma dynimport _wrap_DjondbConnection_rollbackTransaction _wrap_DjondbConnection_rollbackTransaction ""
extern void (*_wrap_DjondbConnection_rollbackTransaction)(void*);
static void (*x_wrap_DjondbConnection_rollbackTransaction)(void*) = _wrap_DjondbConnection_rollbackTransaction;

void
·_swig_wrap_DjondbConnection_rollbackTransaction(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_rollbackTransaction, &p);
}



#pragma dynimport _wrap_DjondbConnection_open _wrap_DjondbConnection_open ""
extern void (*_wrap_DjondbConnection_open)(void*);
static void (*x_wrap_DjondbConnection_open)(void*) = _wrap_DjondbConnection_open;

void
·_swig_wrap_DjondbConnection_open(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_open, &p);
}



#pragma dynimport _wrap_DjondbConnection_close _wrap_DjondbConnection_close ""
extern void (*_wrap_DjondbConnection_close)(void*);
static void (*x_wrap_DjondbConnection_close)(void*) = _wrap_DjondbConnection_close;

void
·_swig_wrap_DjondbConnection_close(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_close, &p);
}



#pragma dynimport _wrap_DjondbConnection_internalClose _wrap_DjondbConnection_internalClose ""
extern void (*_wrap_DjondbConnection_internalClose)(void*);
static void (*x_wrap_DjondbConnection_internalClose)(void*) = _wrap_DjondbConnection_internalClose;

void
·_swig_wrap_DjondbConnection_internalClose(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_internalClose, &p);
}



#pragma dynimport _wrap_DjondbConnection_isOpen _wrap_DjondbConnection_isOpen ""
extern void (*_wrap_DjondbConnection_isOpen)(void*);
static void (*x_wrap_DjondbConnection_isOpen)(void*) = _wrap_DjondbConnection_isOpen;

void
·_swig_wrap_DjondbConnection_isOpen(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_isOpen, &p);
}



#pragma dynimport _wrap_DjondbConnection_shutdown _wrap_DjondbConnection_shutdown ""
extern void (*_wrap_DjondbConnection_shutdown)(void*);
static void (*x_wrap_DjondbConnection_shutdown)(void*) = _wrap_DjondbConnection_shutdown;

void
·_swig_wrap_DjondbConnection_shutdown(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_shutdown, &p);
}



#pragma dynimport _wrap_DjondbConnection_insert__SWIG_0 _wrap_DjondbConnection_insert__SWIG_0 ""
extern void (*_wrap_DjondbConnection_insert__SWIG_0)(void*);
static void (*x_wrap_DjondbConnection_insert__SWIG_0)(void*) = _wrap_DjondbConnection_insert__SWIG_0;

void
·_swig_wrap_DjondbConnection_insert__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_insert__SWIG_0, &p);
}



#pragma dynimport _wrap_DjondbConnection_insert__SWIG_1 _wrap_DjondbConnection_insert__SWIG_1 ""
extern void (*_wrap_DjondbConnection_insert__SWIG_1)(void*);
static void (*x_wrap_DjondbConnection_insert__SWIG_1)(void*) = _wrap_DjondbConnection_insert__SWIG_1;

void
·_swig_wrap_DjondbConnection_insert__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_insert__SWIG_1, &p);
}



#pragma dynimport _wrap_DjondbConnection_findByKey__SWIG_0 _wrap_DjondbConnection_findByKey__SWIG_0 ""
extern void (*_wrap_DjondbConnection_findByKey__SWIG_0)(void*);
static void (*x_wrap_DjondbConnection_findByKey__SWIG_0)(void*) = _wrap_DjondbConnection_findByKey__SWIG_0;

void
·_swig_wrap_DjondbConnection_findByKey__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_findByKey__SWIG_0, &p);
}



#pragma dynimport _wrap_DjondbConnection_findByKey__SWIG_1 _wrap_DjondbConnection_findByKey__SWIG_1 ""
extern void (*_wrap_DjondbConnection_findByKey__SWIG_1)(void*);
static void (*x_wrap_DjondbConnection_findByKey__SWIG_1)(void*) = _wrap_DjondbConnection_findByKey__SWIG_1;

void
·_swig_wrap_DjondbConnection_findByKey__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_findByKey__SWIG_1, &p);
}



#pragma dynimport _wrap_DjondbConnection_find__SWIG_0 _wrap_DjondbConnection_find__SWIG_0 ""
extern void (*_wrap_DjondbConnection_find__SWIG_0)(void*);
static void (*x_wrap_DjondbConnection_find__SWIG_0)(void*) = _wrap_DjondbConnection_find__SWIG_0;

void
·_swig_wrap_DjondbConnection_find__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_find__SWIG_0, &p);
}



#pragma dynimport _wrap_DjondbConnection_find__SWIG_1 _wrap_DjondbConnection_find__SWIG_1 ""
extern void (*_wrap_DjondbConnection_find__SWIG_1)(void*);
static void (*x_wrap_DjondbConnection_find__SWIG_1)(void*) = _wrap_DjondbConnection_find__SWIG_1;

void
·_swig_wrap_DjondbConnection_find__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_find__SWIG_1, &p);
}



#pragma dynimport _wrap_DjondbConnection_find__SWIG_2 _wrap_DjondbConnection_find__SWIG_2 ""
extern void (*_wrap_DjondbConnection_find__SWIG_2)(void*);
static void (*x_wrap_DjondbConnection_find__SWIG_2)(void*) = _wrap_DjondbConnection_find__SWIG_2;

void
·_swig_wrap_DjondbConnection_find__SWIG_2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_find__SWIG_2, &p);
}



#pragma dynimport _wrap_DjondbConnection_find__SWIG_3 _wrap_DjondbConnection_find__SWIG_3 ""
extern void (*_wrap_DjondbConnection_find__SWIG_3)(void*);
static void (*x_wrap_DjondbConnection_find__SWIG_3)(void*) = _wrap_DjondbConnection_find__SWIG_3;

void
·_swig_wrap_DjondbConnection_find__SWIG_3(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_find__SWIG_3, &p);
}



#pragma dynimport _wrap_DjondbConnection_find__SWIG_4 _wrap_DjondbConnection_find__SWIG_4 ""
extern void (*_wrap_DjondbConnection_find__SWIG_4)(void*);
static void (*x_wrap_DjondbConnection_find__SWIG_4)(void*) = _wrap_DjondbConnection_find__SWIG_4;

void
·_swig_wrap_DjondbConnection_find__SWIG_4(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_find__SWIG_4, &p);
}



#pragma dynimport _wrap_DjondbConnection_find__SWIG_5 _wrap_DjondbConnection_find__SWIG_5 ""
extern void (*_wrap_DjondbConnection_find__SWIG_5)(void*);
static void (*x_wrap_DjondbConnection_find__SWIG_5)(void*) = _wrap_DjondbConnection_find__SWIG_5;

void
·_swig_wrap_DjondbConnection_find__SWIG_5(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_find__SWIG_5, &p);
}



#pragma dynimport _wrap_DjondbConnection_update__SWIG_0 _wrap_DjondbConnection_update__SWIG_0 ""
extern void (*_wrap_DjondbConnection_update__SWIG_0)(void*);
static void (*x_wrap_DjondbConnection_update__SWIG_0)(void*) = _wrap_DjondbConnection_update__SWIG_0;

void
·_swig_wrap_DjondbConnection_update__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_update__SWIG_0, &p);
}



#pragma dynimport _wrap_DjondbConnection_update__SWIG_1 _wrap_DjondbConnection_update__SWIG_1 ""
extern void (*_wrap_DjondbConnection_update__SWIG_1)(void*);
static void (*x_wrap_DjondbConnection_update__SWIG_1)(void*) = _wrap_DjondbConnection_update__SWIG_1;

void
·_swig_wrap_DjondbConnection_update__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_update__SWIG_1, &p);
}



#pragma dynimport _wrap_DjondbConnection_remove _wrap_DjondbConnection_remove ""
extern void (*_wrap_DjondbConnection_remove)(void*);
static void (*x_wrap_DjondbConnection_remove)(void*) = _wrap_DjondbConnection_remove;

void
·_swig_wrap_DjondbConnection_remove(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_remove, &p);
}



#pragma dynimport _wrap_DjondbConnection_executeQuery _wrap_DjondbConnection_executeQuery ""
extern void (*_wrap_DjondbConnection_executeQuery)(void*);
static void (*x_wrap_DjondbConnection_executeQuery)(void*) = _wrap_DjondbConnection_executeQuery;

void
·_swig_wrap_DjondbConnection_executeQuery(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_executeQuery, &p);
}



#pragma dynimport _wrap_DjondbConnection_executeUpdate _wrap_DjondbConnection_executeUpdate ""
extern void (*_wrap_DjondbConnection_executeUpdate)(void*);
static void (*x_wrap_DjondbConnection_executeUpdate)(void*) = _wrap_DjondbConnection_executeUpdate;

void
·_swig_wrap_DjondbConnection_executeUpdate(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_executeUpdate, &p);
}



#pragma dynimport _wrap_DjondbConnection_dropNamespace _wrap_DjondbConnection_dropNamespace ""
extern void (*_wrap_DjondbConnection_dropNamespace)(void*);
static void (*x_wrap_DjondbConnection_dropNamespace)(void*) = _wrap_DjondbConnection_dropNamespace;

void
·_swig_wrap_DjondbConnection_dropNamespace(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_dropNamespace, &p);
}



#pragma dynimport _wrap_DjondbConnection_dbs _wrap_DjondbConnection_dbs ""
extern void (*_wrap_DjondbConnection_dbs)(void*);
static void (*x_wrap_DjondbConnection_dbs)(void*) = _wrap_DjondbConnection_dbs;

void
·_swig_wrap_DjondbConnection_dbs(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_dbs, &p);
}



#pragma dynimport _wrap_DjondbConnection_namespaces _wrap_DjondbConnection_namespaces ""
extern void (*_wrap_DjondbConnection_namespaces)(void*);
static void (*x_wrap_DjondbConnection_namespaces)(void*) = _wrap_DjondbConnection_namespaces;

void
·_swig_wrap_DjondbConnection_namespaces(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_namespaces, &p);
}



#pragma dynimport _wrap_DjondbConnection_host _wrap_DjondbConnection_host ""
extern void (*_wrap_DjondbConnection_host)(void*);
static void (*x_wrap_DjondbConnection_host)(void*) = _wrap_DjondbConnection_host;

void
·_swig_wrap_DjondbConnection_host(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnection_host, &p);
}



#pragma dynimport _wrap_new_DjondbCursor__SWIG_0 _wrap_new_DjondbCursor__SWIG_0 ""
extern void (*_wrap_new_DjondbCursor__SWIG_0)(void*);
static void (*x_wrap_new_DjondbCursor__SWIG_0)(void*) = _wrap_new_DjondbCursor__SWIG_0;

void
·_swig_wrap_new_DjondbCursor__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_DjondbCursor__SWIG_0, &p);
}



#pragma dynimport _wrap_new_DjondbCursor__SWIG_1 _wrap_new_DjondbCursor__SWIG_1 ""
extern void (*_wrap_new_DjondbCursor__SWIG_1)(void*);
static void (*x_wrap_new_DjondbCursor__SWIG_1)(void*) = _wrap_new_DjondbCursor__SWIG_1;

void
·_swig_wrap_new_DjondbCursor__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_DjondbCursor__SWIG_1, &p);
}



#pragma dynimport _wrap_delete_DjondbCursor _wrap_delete_DjondbCursor ""
extern void (*_wrap_delete_DjondbCursor)(void*);
static void (*x_wrap_delete_DjondbCursor)(void*) = _wrap_delete_DjondbCursor;

void
·_swig_wrap_delete_DjondbCursor(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_DjondbCursor, &p);
}



#pragma dynimport _wrap_DjondbCursor_next _wrap_DjondbCursor_next ""
extern void (*_wrap_DjondbCursor_next)(void*);
static void (*x_wrap_DjondbCursor_next)(void*) = _wrap_DjondbCursor_next;

void
·_swig_wrap_DjondbCursor_next(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbCursor_next, &p);
}



#pragma dynimport _wrap_DjondbCursor_previous _wrap_DjondbCursor_previous ""
extern void (*_wrap_DjondbCursor_previous)(void*);
static void (*x_wrap_DjondbCursor_previous)(void*) = _wrap_DjondbCursor_previous;

void
·_swig_wrap_DjondbCursor_previous(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbCursor_previous, &p);
}



#pragma dynimport _wrap_DjondbCursor_current _wrap_DjondbCursor_current ""
extern void (*_wrap_DjondbCursor_current)(void*);
static void (*x_wrap_DjondbCursor_current)(void*) = _wrap_DjondbCursor_current;

void
·_swig_wrap_DjondbCursor_current(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbCursor_current, &p);
}



#pragma dynimport _wrap_DjondbCursor_length _wrap_DjondbCursor_length ""
extern void (*_wrap_DjondbCursor_length)(void*);
static void (*x_wrap_DjondbCursor_length)(void*) = _wrap_DjondbCursor_length;

void
·_swig_wrap_DjondbCursor_length(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbCursor_length, &p);
}



#pragma dynimport _wrap_DjondbCursor_releaseCursor _wrap_DjondbCursor_releaseCursor ""
extern void (*_wrap_DjondbCursor_releaseCursor)(void*);
static void (*x_wrap_DjondbCursor_releaseCursor)(void*) = _wrap_DjondbCursor_releaseCursor;

void
·_swig_wrap_DjondbCursor_releaseCursor(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbCursor_releaseCursor, &p);
}



#pragma dynimport _wrap_DjondbCursor_seek _wrap_DjondbCursor_seek ""
extern void (*_wrap_DjondbCursor_seek)(void*);
static void (*x_wrap_DjondbCursor_seek)(void*) = _wrap_DjondbCursor_seek;

void
·_swig_wrap_DjondbCursor_seek(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbCursor_seek, &p);
}



#pragma dynimport _wrap_ConnectionReference__connection_set _wrap_ConnectionReference__connection_set ""
extern void (*_wrap_ConnectionReference__connection_set)(void*);
static void (*x_wrap_ConnectionReference__connection_set)(void*) = _wrap_ConnectionReference__connection_set;

void
·_swig_wrap_ConnectionReference__connection_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ConnectionReference__connection_set, &p);
}



#pragma dynimport _wrap_ConnectionReference__connection_get _wrap_ConnectionReference__connection_get ""
extern void (*_wrap_ConnectionReference__connection_get)(void*);
static void (*x_wrap_ConnectionReference__connection_get)(void*) = _wrap_ConnectionReference__connection_get;

void
·_swig_wrap_ConnectionReference__connection_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ConnectionReference__connection_get, &p);
}



#pragma dynimport _wrap_ConnectionReference__references_set _wrap_ConnectionReference__references_set ""
extern void (*_wrap_ConnectionReference__references_set)(void*);
static void (*x_wrap_ConnectionReference__references_set)(void*) = _wrap_ConnectionReference__references_set;

void
·_swig_wrap_ConnectionReference__references_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ConnectionReference__references_set, &p);
}



#pragma dynimport _wrap_ConnectionReference__references_get _wrap_ConnectionReference__references_get ""
extern void (*_wrap_ConnectionReference__references_get)(void*);
static void (*x_wrap_ConnectionReference__references_get)(void*) = _wrap_ConnectionReference__references_get;

void
·_swig_wrap_ConnectionReference__references_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ConnectionReference__references_get, &p);
}



#pragma dynimport _wrap_new_ConnectionReference _wrap_new_ConnectionReference ""
extern void (*_wrap_new_ConnectionReference)(void*);
static void (*x_wrap_new_ConnectionReference)(void*) = _wrap_new_ConnectionReference;

void
·_swig_wrap_new_ConnectionReference(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_ConnectionReference, &p);
}



#pragma dynimport _wrap_delete_ConnectionReference _wrap_delete_ConnectionReference ""
extern void (*_wrap_delete_ConnectionReference)(void*);
static void (*x_wrap_delete_ConnectionReference)(void*) = _wrap_delete_ConnectionReference;

void
·_swig_wrap_delete_ConnectionReference(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_ConnectionReference, &p);
}



#pragma dynimport _wrap_new_DjondbConnectionManager _wrap_new_DjondbConnectionManager ""
extern void (*_wrap_new_DjondbConnectionManager)(void*);
static void (*x_wrap_new_DjondbConnectionManager)(void*) = _wrap_new_DjondbConnectionManager;

void
·_swig_wrap_new_DjondbConnectionManager(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_DjondbConnectionManager, &p);
}



#pragma dynimport _wrap_delete_DjondbConnectionManager _wrap_delete_DjondbConnectionManager ""
extern void (*_wrap_delete_DjondbConnectionManager)(void*);
static void (*x_wrap_delete_DjondbConnectionManager)(void*) = _wrap_delete_DjondbConnectionManager;

void
·_swig_wrap_delete_DjondbConnectionManager(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_DjondbConnectionManager, &p);
}



#pragma dynimport _wrap_DjondbConnectionManager_getConnection__SWIG_0 _wrap_DjondbConnectionManager_getConnection__SWIG_0 ""
extern void (*_wrap_DjondbConnectionManager_getConnection__SWIG_0)(void*);
static void (*x_wrap_DjondbConnectionManager_getConnection__SWIG_0)(void*) = _wrap_DjondbConnectionManager_getConnection__SWIG_0;

void
·_swig_wrap_DjondbConnectionManager_getConnection__SWIG_0(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnectionManager_getConnection__SWIG_0, &p);
}



#pragma dynimport _wrap_DjondbConnectionManager_getConnection__SWIG_1 _wrap_DjondbConnectionManager_getConnection__SWIG_1 ""
extern void (*_wrap_DjondbConnectionManager_getConnection__SWIG_1)(void*);
static void (*x_wrap_DjondbConnectionManager_getConnection__SWIG_1)(void*) = _wrap_DjondbConnectionManager_getConnection__SWIG_1;

void
·_swig_wrap_DjondbConnectionManager_getConnection__SWIG_1(struct {
  uint8 x[(2 * SWIG_PARM_SIZE) + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnectionManager_getConnection__SWIG_1, &p);
}



#pragma dynimport _wrap_DjondbConnectionManager_releaseConnection _wrap_DjondbConnectionManager_releaseConnection ""
extern void (*_wrap_DjondbConnectionManager_releaseConnection)(void*);
static void (*x_wrap_DjondbConnectionManager_releaseConnection)(void*) = _wrap_DjondbConnectionManager_releaseConnection;

void
·_swig_wrap_DjondbConnectionManager_releaseConnection(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DjondbConnectionManager_releaseConnection, &p);
}



